// Copyright 2022 Jose Pablo Ramirez (@jpe230)
// SPDX-License-Identifier: GPL-2.0-or-later#undef RGB_DI_PIN

#define RGBLIGHT_DI_PIN E6

#define RGB_DI_PIN 17U
#define RGB_MATRIX_LED_COUNT 1
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#define RGB_MATRIX_DISABLE_KEYCODES
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define RGB_MATRIX_DEFAULT_MODE ENABLE_RGB_MATRIX_CYCLE_ALL
