VIA_ENABLE = yes

SRC = matrix.c jpe230.c
QUANTUM_LIB_SRC =

CONSOLE_ENABLE = yes
BOOTMAGIC_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
RGBLIGHT_ENABLE = yes
EXTRAKEY_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
WPM_ENABLE = yes

MOUSEKEY_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes
