#pragma once
/* Copyright 2022 Jose Pablo Ramirez <jp.ramangulo@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#define ENABLE_RGB_MATRIX_ALPHAS_MODS
#define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_BREATHING
#define ENABLE_RGB_MATRIX_BAND_SAT
#define ENABLE_RGB_MATRIX_BAND_VAL
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#define ENABLE_RGB_MATRIX_DUAL_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_BEACON
#define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define ENABLE_RGB_MATRIX_RAINDROPS
#define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define ENABLE_RGB_MATRIX_HUE_BREATHING
#define ENABLE_RGB_MATRIX_HUE_PENDULUM
#define ENABLE_RGB_MATRIX_HUE_WAVE
#define ENABLE_RGB_MATRIX_PIXEL_RAIN
#define ENABLE_RGB_MATRIX_PIXEL_FLOW
#define ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_SPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

#define ALPHAS_MODS_STR
#ifdef ENABLE_RGB_MATRIX_ALPHAS_MODS
#undef ALPHAS_MODS_STR
#define ALPHAS_MODS_STR "AlphaMods",
#endif

#define GRADIENT_UP_DOWN_STR
#ifdef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#undef GRADIENT_UP_DOWN_STR
#define GRADIENT_UP_DOWN_STR "GradientUD",
#endif

#define GRADIENT_LEFT_RIGHT_STR
#ifdef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#undef GRADIENT_LEFT_RIGHT_STR
#define GRADIENT_LEFT_RIGHT_STR "GradientLR",
#endif

#define BREATHING_STR
#ifdef ENABLE_RGB_MATRIX_BREATHING
#undef BREATHING_STR
#define BREATHING_STR "Breathing",
#endif

#define BAND_SAT_STR
#ifdef ENABLE_RGB_MATRIX_BAND_SAT
#undef BAND_SAT_STR
#define BAND_SAT_STR "BandSat",
#endif

#define BAND_VAL_STR
#ifdef ENABLE_RGB_MATRIX_BAND_VAL
#undef BAND_VAL_STR
#define BAND_VAL_STR "BandVal",
#endif

#define BAND_PINWHEEL_SAT_STR
#ifdef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#undef BAND_PINWHEEL_SAT_STR
#define BAND_PINWHEEL_SAT_STR "PWSat",
#endif

#define BAND_PINWHEEL_VAL_STR
#ifdef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#undef BAND_PINWHEEL_VAL_STR
#define BAND_PINWHEEL_VAL_STR "PWVal",
#endif

#define BAND_SPIRAL_SAT_STR
#ifdef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#undef BAND_SPIRAL_SAT_STR
#define BAND_SPIRAL_SAT_STR "SpiSat",
#endif

#define BAND_SPIRAL_VAL_STR
#ifdef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#undef BAND_SPIRAL_VAL_STR
#define BAND_SPIRAL_VAL_STR "SpiVal",
#endif

#define CYCLE_ALL_STR
#ifdef ENABLE_RGB_MATRIX_CYCLE_ALL
#undef CYCLE_ALL_STR
#define CYCLE_ALL_STR "Cycle",
#endif

#define CYCLE_LEFT_RIGHT_STR
#ifdef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#undef CYCLE_LEFT_RIGHT_STR
#define CYCLE_LEFT_RIGHT_STR "CycleLR",
#endif

#define CYCLE_UP_DOWN_STR
#ifdef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
#undef CYCLE_UP_DOWN_STR
#define CYCLE_UP_DOWN_STR "CycleUP",
#endif

#define RAINBOW_MOVING_CHEVRON_STR
#ifdef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#undef RAINBOW_MOVING_CHEVRON_STR
#define RAINBOW_MOVING_CHEVRON_STR "RbMovChev",
#endif

#define CYCLE_OUT_IN_STR
#ifdef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
#undef CYCLE_OUT_IN_STR
#define CYCLE_OUT_IN_STR "CycleOI",
#endif

#define CYCLE_OUT_IN_DUAL_STR
#ifdef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#undef CYCLE_OUT_IN_DUAL_STR
#define CYCLE_OUT_IN_DUAL_STR "CycleOID",
#endif

#define CYCLE_PINWHEEL_STR
#ifdef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
#undef CYCLE_PINWHEEL_STR
#define CYCLE_PINWHEEL_STR "CyclePW",
#endif

#define CYCLE_SPIRAL_STR
#ifdef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
#undef CYCLE_SPIRAL_STR
#define CYCLE_SPIRAL_STR "CycleSpiral",
#endif

#define DUAL_BEACON_STR
#ifdef ENABLE_RGB_MATRIX_DUAL_BEACON
#undef DUAL_BEACON_STR
#define DUAL_BEACON_STR "DualBeacon",
#endif

#define RAINBOW_BEACON_STR
#ifdef ENABLE_RGB_MATRIX_RAINBOW_BEACON
#undef RAINBOW_BEACON_STR
#define RAINBOW_BEACON_STR "RbBeacon",
#endif

#define RAINBOW_PINWHEELS_STR
#ifdef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#undef RAINBOW_PINWHEELS_STR
#define RAINBOW_PINWHEELS_STR "RbPinW",
#endif

#define RAINDROPS_STR
#ifdef ENABLE_RGB_MATRIX_RAINDROPS
#undef RAINDROPS_STR
#define RAINDROPS_STR "Raindps",
#endif

#define JELLYBEAN_RAINDROPS_STR
#ifdef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#undef JELLYBEAN_RAINDROPS_STR
#define JELLYBEAN_RAINDROPS_STR "JbRain",
#endif

#define HUE_BREATHING_STR
#ifdef ENABLE_RGB_MATRIX_HUE_BREATHING
#undef HUE_BREATHING_STR
#define HUE_BREATHING_STR "HBreath",
#endif

#define HUE_PENDULUM_STR
#ifdef ENABLE_RGB_MATRIX_HUE_PENDULUM
#undef HUE_PENDULUM_STR
#define HUE_PENDULUM_STR "HPendu",
#endif

#define HUE_WAVE_STR
#ifdef ENABLE_RGB_MATRIX_HUE_WAVE
#undef HUE_WAVE_STR
#define HUE_WAVE_STR "HueWave",
#endif

#define PIXEL_RAIN_STR
#ifdef ENABLE_RGB_MATRIX_PIXEL_RAIN
#undef PIXEL_RAIN_STR
#define PIXEL_RAIN_STR "PixRain",
#endif

#define PIXEL_FLOW_STR
#ifdef ENABLE_RGB_MATRIX_PIXEL_FLOW
#undef PIXEL_FLOW_STR
#define PIXEL_FLOW_STR "PixFlow",
#endif

#define PIXEL_FRACTAL_STR
#ifdef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
#undef PIXEL_FRACTAL_STR
#define PIXEL_FRACTAL_STR "PixFractal",
#endif

#define TYPING_HEATMAP_STR
#ifdef ENABLE_RGB_MATRIX_TYPING_HEATMAP
#undef TYPING_HEATMAP_STR
#define TYPING_HEATMAP_STR "Heatmap",
#endif

#define DIGITAL_RAIN_STR
#ifdef ENABLE_RGB_MATRIX_DIGITAL_RAIN
#undef DIGITAL_RAIN_STR
#define DIGITAL_RAIN_STR "DRain",
#endif

#define SOLID_REACTIVE_SIMPLE_STR
#ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#undef SOLID_REACTIVE_SIMPLE_STR
#define SOLID_REACTIVE_SIMPLE_STR "SRSimple",
#endif

#define SOLID_REACTIVE_STR
#ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE
#undef SOLID_REACTIVE_STR
#define SOLID_REACTIVE_STR "SR",
#endif

#define SOLID_REACTIVE_WIDE_STR
#ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#undef SOLID_REACTIVE_WIDE_STR
#define SOLID_REACTIVE_WIDE_STR "SRWide",
#endif

#define SOLID_REACTIVE_MULTIWIDE_STR
#ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#undef SOLID_REACTIVE_MULTIWIDE_STR
#define SOLID_REACTIVE_MULTIWIDE_STR "SRMultiW",
#endif

#define SOLID_REACTIVE_CROSS_STR
#ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
#undef SOLID_REACTIVE_CROSS_STR
#define SOLID_REACTIVE_CROSS_STR "SRCross",
#endif

#define SOLID_REACTIVE_MULTICROSS_STR
#ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
#undef SOLID_REACTIVE_MULTICROSS_STR
#define SOLID_REACTIVE_MULTICROSS_STR "SRMultiC",
#endif

#define SOLID_REACTIVE_NEXUS_STR
#ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
#undef SOLID_REACTIVE_NEXUS_STR
#define SOLID_REACTIVE_NEXUS_STR "SRNexus",
#endif

#define SOLID_REACTIVE_MULTINEXUS_STR
#ifdef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
#undef SOLID_REACTIVE_MULTINEXUS_STR
#define SOLID_REACTIVE_MULTINEXUS_STR "SRMNexus",
#endif

#define SPLASH_STR
#ifdef ENABLE_RGB_MATRIX_SPLASH
#undef SPLASH_STR
#define SPLASH_STR "Splash",
#endif

#define MULTISPLASH_STR
#ifdef ENABLE_RGB_MATRIX_MULTISPLASH
#undef MULTISPLASH_STR
#define MULTISPLASH_STR "MSplash",
#endif

#define SOLID_SPLASH_STR
#ifdef ENABLE_RGB_MATRIX_SOLID_SPLASH
#undef SOLID_SPLASH_STR
#define SOLID_SPLASH_STR "SSplash",
#endif

#define SOLID_MULTISPLASH_STR
#ifdef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
#undef SOLID_MULTISPLASH_STR
#define SOLID_MULTISPLASH_STR "SMSplash",
#endif


# define VALID_RGB_MODES \
        ALPHAS_MODS_STR \
        GRADIENT_UP_DOWN_STR \
        GRADIENT_LEFT_RIGHT_STR \
        BREATHING_STR \
        BAND_SAT_STR \
        BAND_VAL_STR \
        BAND_PINWHEEL_SAT_STR \
        BAND_PINWHEEL_VAL_STR \
        BAND_SPIRAL_SAT_STR \
        BAND_SPIRAL_VAL_STR \
        CYCLE_ALL_STR \
        CYCLE_LEFT_RIGHT_STR \
        CYCLE_UP_DOWN_STR \
        RAINBOW_MOVING_CHEVRON_STR \
        CYCLE_OUT_IN_STR \
        CYCLE_OUT_IN_DUAL_STR \
        CYCLE_PINWHEEL_STR \
        CYCLE_SPIRAL_STR \
        DUAL_BEACON_STR \
        RAINBOW_BEACON_STR \
        RAINBOW_PINWHEELS_STR \
        RAINDROPS_STR \
        JELLYBEAN_RAINDROPS_STR \
        HUE_BREATHING_STR \
        HUE_PENDULUM_STR \
        HUE_WAVE_STR \
        PIXEL_RAIN_STR \
        PIXEL_FLOW_STR \
        PIXEL_FRACTAL_STR \
        TYPING_HEATMAP_STR \
        DIGITAL_RAIN_STR \
        SOLID_REACTIVE_SIMPLE_STR \
        SOLID_REACTIVE_STR \
        SOLID_REACTIVE_WIDE_STR \
        SOLID_REACTIVE_MULTIWIDE_STR \
        SOLID_REACTIVE_CROSS_STR \
        SOLID_REACTIVE_MULTICROSS_STR \
        SOLID_REACTIVE_NEXUS_STR \
        SOLID_REACTIVE_MULTINEXUS_STR \
        SPLASH_STR \
        MULTISPLASH_STR \
        SOLID_SPLASH_STR \
        SOLID_MULTISPLASH_STR \

#ifdef __cplusplus
} /*extern "C"*/
#endif

