#define SECRET_LAYERS
#define SECRET_LAYER_COUNT 0
#define SECRET_KEYCODES
#define SECRET_KEYMAP
#define SECRET_INDICATORS
#define SECRET_KEY_STRING
#define SECRET_OLED
#define SECRET_LAYER_HANDLING
#define SECRET_KC_HANDLING
#define SECRET_LAYER_STRINGS
#define PASSWORD
#define PASSWORD_LEN
#define TIMESTEPS